apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: 80-80
    port: {{ .Values.sourcePort }}
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP